[package]
name = 'mrn'
version = '0.1.2'
authors = ['AlseinX <xyh951115@live.com>']
edition = '2018'

[lib]
crate-type = [
    'lib',
    'cdylib',
]

[dependencies]
clap = '2.33'
rayon = '1.3'
chardet = '0.2'
encoding = '0.2'
regex = '1.3'
