[package]
name = 'mrn'
version = '0.1.0'
authors = ['AlseinX <xyh951115@live.com>']
edition = '2018'

[lib]
name = 'mrn'
crate-type = ['cdylib']

[dependencies]
clap = '2.33'
rayon = '1.3'
futures = '0.3'
chardet = '0.2'
encoding = '0.2'
